server:
  port: 8078
  servlet:
    context-path: /dib

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=false;INIT=CREATE SCHEMA IF NOT EXISTS dib
    driver-class-name: org.h2.Driver
    username: sa
    password:
    initialize: true
#    data: classpath:data.sql
    hikari:
      maximumPoolSize: 10
      minimumIdle: 5
      maxLifetime: 2000000
      connectionTimeout: 30000
      idleTimeout: 30000
      connection-test-query: SELECT 1
      poolName: DibServiceH2HikariPool
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      org.hibernate.flushMode: COMMIT
      hibernate:
        show_sql: true
        format_sql: true
  jackson:
    serialization:
      write_dates_as_timestamps: false
  flyway:
    enabled: true
beer.api.url.base: https://api.punkapi.com/v2/beers/