server:
  port: 8078
  servlet:
    context-path: /dib
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dib?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: Ognjen1203
  jpa:
    hibernate:
      ddl-auto: validate
    dialect: org.hibernate.dialect.MySQLDialect
flyway:
  enabled: false
beer.api.url.base: https://api.punkapi.com/v2/beers/